# Generated by Django 6.0.4 on 2026-04-12 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overstay', '超时停放'), ('security', '安全事件'), ('payment', '支付异常'), ('device', '设备故障'), ('system', '系统告警')], max_length=12, verbose_name='告警类型')),
                ('title', models.CharField(help_text='如：设备离线: B区摄像头#4', max_length=100, verbose_name='告警标题')),
                ('detail', models.TextField(blank=True, default='', help_text='Feed 描述文本', verbose_name='详细描述')),
                ('location', models.CharField(blank=True, default='', help_text='如：B2层-A区, 南出口', max_length=100, verbose_name='位置')),
                ('severity', models.CharField(choices=[('emergency', '紧急'), ('warning', '警告'), ('info', '提示')], default='info', max_length=12, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('investigating', '调查中'), ('resolved', '已解决'), ('dismissed', '已忽略')], default='pending', max_length=15, verbose_name='处理状态')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统预警',
                'verbose_name_plural': '系统预警',
                'db_table': 'sentinel_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(help_text='格式如 #ST-9921，系统自动生成', max_length=20, unique=True, verbose_name='工单编号')),
                ('ticket_type', models.CharField(choices=[('device_fault', '设备故障'), ('complaint', '服务投诉'), ('suggestion', '改进建议')], max_length=15, verbose_name='反馈类型')),
                ('title', models.CharField(help_text='如：设备故障：4层传感器', max_length=100, verbose_name='标题')),
                ('description', models.TextField(help_text='反馈表单中的文本域内容', verbose_name='详细描述')),
                ('attachment', models.ImageField(blank=True, help_text='证明材料照片或截图', null=True, upload_to='tickets/', verbose_name='附件')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('reviewing', '审核中'), ('resolved', '已解决'), ('closed', '已关闭')], default='submitted', max_length=12, verbose_name='工单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '用户工单',
                'verbose_name_plural': '用户工单',
                'db_table': 'sentinel_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
