# Generated by Django 6.0.4 on 2026-04-12 18:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, help_text='注册页(_14)中的 11 位手机号码', max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, help_text='个人中心(_5)用户头像', null=True, upload_to='avatars/', verbose_name='头像')),
                ('is_vip', models.BooleanField(default=False, help_text='个人中心(_5)通行证状态标签', verbose_name='高级会员')),
                ('status', models.CharField(choices=[('active', '活跃'), ('banned', '已封禁'), ('inactive', '未激活')], default='active', help_text='用户管理(_10)表格中的状态列', max_length=10, verbose_name='账户状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sentinel_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='格式如：京A·12345', max_length=20, unique=True, verbose_name='车牌号')),
                ('brand', models.CharField(help_text='如：特斯拉、路虎', max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, default='', help_text='如：Model 3、揽胜运动版', max_length=50, verbose_name='型号')),
                ('color', models.CharField(blank=True, default='', help_text='反向寻车结果中的车辆颜色', max_length=20, verbose_name='颜色')),
                ('is_primary', models.BooleanField(default=False, help_text='个人中心(_5)车辆列表中的"默认"标签', verbose_name='默认车辆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='车主')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
                'db_table': 'sentinel_vehicle',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
