# Generated by Django 6.0.4 on 2026-04-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='用于生成 TOTP 二维码的 32 位随机密钥', max_length=32, null=True, verbose_name='2FA 密钥'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='是否启用 TOTP 双因子认证', verbose_name='开启两步验证'),
        ),
    ]
