# Generated by Django 6.0.4 on 2026-05-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_drop_alert_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text='是否通过模拟进场创建的临时车辆，不展示在用户个人车辆列表中', verbose_name='模拟车辆'),
        ),
    ]
