# Generated by Django 6.0.4 on 2026-04-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：道闸 1, 入口摄像头 2', max_length=50, verbose_name='设备名称')),
                ('device_type', models.CharField(choices=[('gate', '道闸'), ('camera', '摄像头'), ('kiosk', '自助终端'), ('sensor', '传感器')], max_length=15, verbose_name='设备类型')),
                ('location', models.CharField(help_text='如：北入口 - A车道, 1层 - 主电梯大堂', max_length=100, verbose_name='安装位置')),
                ('serial_number', models.CharField(help_text='如：SB-001-N, KS-442-LV1', max_length=50, unique=True, verbose_name='序列号')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '故障'), ('maintenance', '维护中')], default='online', max_length=15, verbose_name='运行状态')),
                ('uptime', models.DecimalField(decimal_places=2, default=100.0, help_text='百分比，如 99.80 表示 99.8%', max_digits=5, verbose_name='正常运行率')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('fault_detail', models.CharField(blank=True, default='', help_text='故障卡片中的 "问题" 字段', max_length=200, verbose_name='故障说明')),
                ('offline_since', models.DateTimeField(blank=True, help_text='故障卡片中的 "离线时长" 推算', null=True, verbose_name='离线起始时间')),
                ('paper_level', models.IntegerField(blank=True, help_text='自助终端纸张余量百分比，如 22', null=True, verbose_name='纸张余量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'sentinel_device',
                'ordering': ['device_type', 'name'],
            },
        ),
    ]
