# Generated by Django 6.0.4 on 2026-04-12 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.CharField(help_text='如 A-12, B2-05, 对应地图网格编号', max_length=20, unique=True, verbose_name='车位编号')),
                ('floor', models.CharField(help_text='如 B1, B2, 1F, 对应楼层切换标签', max_length=10, verbose_name='楼层')),
                ('zone', models.CharField(help_text='如 A区, B区', max_length=10, verbose_name='区域')),
                ('spot_type', models.CharField(choices=[('standard', '标准'), ('compact', '紧凑'), ('ev', '充电桩'), ('vip', 'VIP'), ('accessible', '无障碍')], default='standard', max_length=15, verbose_name='车位类型')),
                ('status', models.CharField(choices=[('free', '空闲'), ('occupied', '已占用'), ('reserved', '已预约'), ('maintenance', '维修中'), ('overstay', '超时')], default='free', max_length=15, verbose_name='当前状态')),
                ('floor_x', models.IntegerField(default=0, verbose_name='地图X坐标')),
                ('floor_y', models.IntegerField(default=0, verbose_name='地图Y坐标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '停车位',
                'verbose_name_plural': '停车位',
                'db_table': 'sentinel_parking_spot',
                'ordering': ['floor', 'zone', 'spot_id'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(verbose_name='入场时间')),
                ('exit_time', models.DateTimeField(blank=True, help_text='为空表示车辆仍在场内', null=True, verbose_name='出场时间')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='单位：元', max_digits=10, verbose_name='停车费用')),
                ('payment_status', models.CharField(choices=[('pending', '未缴费'), ('paid', '已支付'), ('overstay', '超时待缴')], default='pending', max_length=10, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.vehicle', verbose_name='车辆')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parking.parkingspot', verbose_name='车位')),
            ],
            options={
                'verbose_name': '停车会话',
                'verbose_name_plural': '停车会话',
                'db_table': 'sentinel_parking_session',
                'ordering': ['-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='基础费率 + 优选车位附加费 + 预约服务费', max_digits=10, verbose_name='总费用')),
                ('booking_code', models.CharField(help_text='如 SENT-982-A1，确认弹窗中展示', max_length=30, unique=True, verbose_name='预约编号')),
                ('qr_code', models.ImageField(blank=True, help_text='确认后生成的电子凭证', null=True, upload_to='qrcodes/', verbose_name='入场二维码')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=12, verbose_name='预约状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkingspot', verbose_name='车位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '车位预约',
                'verbose_name_plural': '车位预约',
                'db_table': 'sentinel_reservation',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
