# Generated by Django 6.0.4 on 2026-04-18 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(default=1.0, help_text='两个车位间的导航距离（单位：米）', verbose_name='路径距离')),
                ('from_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='parking.parkingspot', verbose_name='起点车位')),
                ('to_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='parking.parkingspot', verbose_name='终点车位')),
            ],
            options={
                'verbose_name': '停车位连接',
                'verbose_name_plural': '停车位连接',
                'db_table': 'sentinel_spot_connection',
                'indexes': [models.Index(fields=['from_spot', 'to_spot'], name='sentinel_sp_from_sp_42ff6a_idx')],
                'unique_together': {('from_spot', 'to_spot')},
            },
        ),
    ]
