# Generated by Django 6.0.4 on 2026-04-19 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_spotconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.CharField(help_text='如 space_A001, space_B005，与 SVG 元素 id 完全对应', max_length=50, unique=True, verbose_name='车位编号(对应SVG ID)')),
                ('status', models.CharField(choices=[('free', '空闲'), ('occupied', '占用')], default='free', help_text='free=空闲, occupied=占用', max_length=20, verbose_name='当前状态')),
                ('current_plate', models.CharField(blank=True, help_text='若为空则表示车位空闲', max_length=20, null=True, verbose_name='当前停放车牌')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后状态更新时间')),
                ('center_x', models.FloatField(blank=True, help_text='车位在 SVG 地图中的中心 X 坐标', null=True, verbose_name='SVG X坐标')),
                ('center_y', models.FloatField(blank=True, help_text='车位在 SVG 地图中的中心 Y 坐标', null=True, verbose_name='SVG Y坐标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parking_spot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space', to='parking.parkingspot', verbose_name='关联停车位')),
            ],
            options={
                'verbose_name': '车位信息(地图渲染)',
                'verbose_name_plural': '车位信息(地图渲染)',
                'db_table': 'parking_space',
                'ordering': ['space_id'],
                'indexes': [models.Index(fields=['status'], name='parking_spa_status_13fb3d_idx'), models.Index(fields=['current_plate'], name='parking_spa_current_76b9ed_idx')],
            },
        ),
    ]
