# Generated by Django 6.0.4 on 2026-04-19 06:26

from django.db import migrations


def create_b_floor_spaces(apps, schema_editor):
    """创建 B1 和 B2 楼层的停车位（基于 A 楼层）"""
    ParkingSpace = apps.get_model('parking', 'ParkingSpace')
    
    # 获取所有 A 楼层停车位
    a_spaces = ParkingSpace.objects.filter(space_id__startswith='space_A').order_by('space_id')
    
    print(f"\n创建 B1 和 B2 停车位... (基于 {a_spaces.count()} 个 A 楼层停车位)")
    
    b1_spaces = []
    b2_spaces = []
    
    for a_space in a_spaces:
        # 提取原始编号 (001, 002 等)
        original_num = a_space.space_id[7:]  # 去掉 'space_A'
        
        # 创建 B1 停车位
        b1_spaces.append(ParkingSpace(
            space_id=f'space_B1{original_num}',
            qr_code_token=f'QR_SPACE_B1{original_num}',
            status='free',  # 直接使用字符串值
            center_x=a_space.center_x,
            center_y=a_space.center_y,
            x=a_space.x,
            y=a_space.y,
            current_plate=None,
            bind_time=None
        ))
        
        # 创建 B2 停车位
        b2_spaces.append(ParkingSpace(
            space_id=f'space_B2{original_num}',
            qr_code_token=f'QR_SPACE_B2{original_num}',
            status='free',  # 直接使用字符串值
            center_x=a_space.center_x,
            center_y=a_space.center_y,
            x=a_space.x,
            y=a_space.y,
            current_plate=None,
            bind_time=None
        ))
    
    # 批量创建
    ParkingSpace.objects.bulk_create(b1_spaces, ignore_conflicts=True)
    ParkingSpace.objects.bulk_create(b2_spaces, ignore_conflicts=True)
    
    # 验证
    b1_count = ParkingSpace.objects.filter(space_id__startswith='space_B1').count()
    b2_count = ParkingSpace.objects.filter(space_id__startswith='space_B2').count()
    total = ParkingSpace.objects.count()
    
    print(f"✅ B1: {b1_count} spaces")
    print(f"✅ B2: {b2_count} spaces")
    print(f"✅ 总计: {total} spaces\n")


def reverse_b_floor_spaces(apps, schema_editor):
    """回滚 - 删除 B1 和 B2 停车位"""
    ParkingSpace = apps.get_model('parking', 'ParkingSpace')
    ParkingSpace.objects.filter(space_id__startswith='space_B1').delete()
    ParkingSpace.objects.filter(space_id__startswith='space_B2').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingspace_qr_code_token'),
    ]

    operations = [
        migrations.RunPython(create_b_floor_spaces, reverse_b_floor_spaces),
    ]
