# Generated by Django 6.0.4 on 2026-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_add_b_floors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspace',
            options={'ordering': ['floor', 'space_id'], 'verbose_name': '车位信息(地图渲染)', 'verbose_name_plural': '车位信息(地图渲染)'},
        ),
        migrations.RemoveIndex(
            model_name='parkingspace',
            name='parking_spa_status_13fb3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingspace',
            name='parking_spa_current_76b9ed_idx',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='floor',
            field=models.CharField(choices=[('B2', '地下二层'), ('B1', '地下一层'), ('1F', '一楼')], default='B2', help_text='停车位所在楼层: B2/B1/1F', max_length=10, verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='space_id',
            field=models.CharField(help_text='如 space_A001, space_B005，与 SVG 元素 id 完全对应', max_length=50, verbose_name='车位编号(对应SVG ID)'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingspace',
            unique_together={('floor', 'space_id')},
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['floor', 'status'], name='parking_spa_floor_ff724f_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspace',
            index=models.Index(fields=['floor', 'current_plate'], name='parking_spa_floor_0b7424_idx'),
        ),
    ]
