# Generated by Django 6.0.4 on 2026-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_parkingspace_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='rotation',
            field=models.IntegerField(default=0, help_text='停车位旋转角度（0度 或 90度）', verbose_name='旋转角度'),
        ),
    ]
