# Generated by Django 6.0.4 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_parkingspace_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='type',
            field=models.BooleanField(
                default=False,
                help_text='true=充电桩停车位, false=普通停车位',
                verbose_name='是否充电桩停车位',
            ),
        ),
    ]
