# Generated by Django 6.0.4 on 2026-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_alter_parkingspace_status_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='is_reserved',
            field=models.BooleanField(default=False, help_text='true=已预约, false=未预约', verbose_name='是否已预约'),
        ),
    ]
