# Generated by Django 6.0.4 on 2026-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_parkingspace_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='reserved_plate',
            field=models.CharField(blank=True, help_text='已预约车位对应的预约车牌号，不代表已实际占用', max_length=20, null=True, verbose_name='预约车牌'),
        ),
    ]
