# Generated by Django 6.0.4 on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models


def cleanup_legacy_parkingspot_refs(apps, schema_editor):
    ParkingSession = apps.get_model('parking', 'ParkingSession')
    Reservation = apps.get_model('parking', 'Reservation')
    SpotConnection = apps.get_model('parking', 'SpotConnection')
    ParkingSpace = apps.get_model('parking', 'ParkingSpace')

    # 先清理依赖 legacy ParkingSpot 的关系数据，避免外键重绑定失败
    ParkingSession.objects.exclude(spot_id__isnull=True).update(spot_id=None)
    Reservation.objects.all().delete()
    SpotConnection.objects.all().delete()

    # 解除 ParkingSpace 到 legacy ParkingSpot 的映射
    if hasattr(ParkingSpace, 'parking_spot_id'):
        ParkingSpace.objects.exclude(parking_spot_id__isnull=True).update(parking_spot_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_parkingspace_reserved_plate'),
    ]

    operations = [
        migrations.RunPython(cleanup_legacy_parkingspot_refs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='parkingsession',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parking.parkingspace', verbose_name='车位'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking.parkingspace', verbose_name='车位'),
        ),
        migrations.AlterField(
            model_name='spotconnection',
            name='from_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='parking.parkingspace', verbose_name='起点车位'),
        ),
        migrations.AlterField(
            model_name='spotconnection',
            name='to_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='parking.parkingspace', verbose_name='终点车位'),
        ),
        migrations.RemoveField(
            model_name='parkingspace',
            name='parking_spot',
        ),
        migrations.DeleteModel(
            name='ParkingSpot',
        ),
    ]
