# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_remove_legacy_parkingspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='离开日期', help_text='不填时默认与预约日期相同'),
        ),
    ]
