# Generated by Copilot on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_add_reservation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='预约创建时使用的支付方式', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', help_text='余额支付的交易流水号，用于取消预约时退款', max_length=64, verbose_name='支付交易ID'),
        ),
    ]
