# Generated by Django 6.0.4 on 2026-05-06 13:16

import uuid
from django.db import migrations


def add_public_locations(apps, schema_editor):
    """为每层楼添加公共位置节点（出入口，地图左上角）。"""
    ParkingSpace = apps.get_model('parking', 'ParkingSpace')

    # Clean up old location records
    ParkingSpace.objects.filter(space_id__startswith='LOC_').delete()

    locations = [
        # === 1F ===
        {'floor': '1F', 'name': '出入口', 'x': 48, 'y': 88, 'center_x': 48, 'center_y': 88},

        # === B1 ===
        {'floor': 'B1', 'name': '出入口', 'x': 48, 'y': 88, 'center_x': 48, 'center_y': 88},

        # === B2 ===
        {'floor': 'B2', 'name': '出入口', 'x': 48, 'y': 88, 'center_x': 48, 'center_y': 88},
    ]

    objs = []
    for loc in locations:
        space_id = f"LOC_{loc['floor']}_{loc['name']}"
        if not ParkingSpace.objects.filter(space_id=space_id, floor=loc['floor']).exists():
            objs.append(ParkingSpace(
                floor=loc['floor'],
                space_id=space_id,
                node_type='location',
                location_name=loc['name'],
                x=loc['x'],
                y=loc['y'],
                center_x=loc['center_x'],
                center_y=loc['center_y'],
                rotation=0,
                qr_code_token=f'LOC-{uuid.uuid4().hex[:16].upper()}',
            ))

    if objs:
        ParkingSpace.objects.bulk_create(objs)


def remove_public_locations(apps, schema_editor):
    ParkingSpace = apps.get_model('parking', 'ParkingSpace')
    ParkingSpace.objects.filter(space_id__startswith='LOC_').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_parking_space_node_type_and_location_name'),
    ]

    operations = [
        migrations.RunPython(add_public_locations, remove_public_locations),
    ]
