# Generated by Django 6.0.4 on 2026-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0018_add_public_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', '-end_date', '-start_time'], 'verbose_name': '车位预约', 'verbose_name_plural': '车位预约'},
        ),
        migrations.RenameIndex(
            model_name='parkingspace',
            new_name='parking_spa_node_ty_1ae00c_idx',
            old_name='parking_spa_node_ty_8c3b67_idx',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='pending_exit_plate',
            field=models.CharField(blank=True, help_text='已缴费待出场的车牌，30分钟内有效', max_length=20, null=True, verbose_name='待出场车牌'),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='pending_exit_time',
            field=models.DateTimeField(blank=True, help_text='用户完成缴费的时间，超过30分钟未出场需重新缴费', null=True, verbose_name='缴费出场时间'),
        ),
    ]
