# Generated by Django 6.0.4 on 2026-04-12 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('hourly_standard', '标准时段（元/小时）'), ('hourly_peak', '高峰时段（元/小时）'), ('grace_entry', '入场宽限期（分钟）'), ('grace_exit', '出场宽限期（分钟）'), ('monthly_commute', '月卡-通勤版'), ('monthly_premium', '月卡-高级版')], max_length=20, unique=True, verbose_name='费率类型')),
                ('value', models.DecimalField(decimal_places=2, help_text='费率值或时长值', max_digits=10, verbose_name='数值')),
                ('unit', models.CharField(help_text='元/小时、分钟、元/月 等', max_length=20, verbose_name='单位')),
                ('description', models.CharField(blank=True, default='', help_text='管理后台卡片中的副标题', max_length=200, verbose_name='规则说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('effective_date', models.DateField(help_text='该规则从何时开始生效', verbose_name='生效日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '定价规则',
                'verbose_name_plural': '定价规则',
                'db_table': 'sentinel_pricing_rule',
                'ordering': ['rate_type'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='系统生成的唯一交易标识', max_length=64, unique=True, verbose_name='交易ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='单位：元', max_digits=10, verbose_name='金额')),
                ('method', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('etc', 'ETC'), ('card', '信用卡'), ('cash', '现金')], max_length=10, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('refunded', '已退款'), ('pending', '处理中')], default='pending', max_length=10, verbose_name='支付状态')),
                ('remark', models.CharField(blank=True, default='', help_text='交易说明或失败原因', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='parking.parkingsession', verbose_name='关联停车会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'sentinel_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', '月卡'), ('yearly', '年卡'), ('basic', '基础版'), ('advanced', '高级版'), ('elite', '尊享版')], max_length=10, verbose_name='套餐类型')),
                ('price', models.DecimalField(decimal_places=2, help_text='单位：元', max_digits=10, verbose_name='价格')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, help_text='到期或手动取消后置为 False', verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订阅计划',
                'verbose_name_plural': '订阅计划',
                'db_table': 'sentinel_subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
