# Generated by Django 6.0.4 on 2026-04-12 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(
                choices=[
                    ('wechat', '微信支付'),
                    ('alipay', '支付宝'),
                    ('card', '银行卡'),
                    ('balance', '余额支付'),
                    ('cash', '现金')
                ],
                max_length=10,
                verbose_name='支付方式'
            ),
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='单位：元', max_digits=10, verbose_name='账户余额')),
                ('total_recharged', models.DecimalField(decimal_places=2, default=0, help_text='历史累计充值总额', max_digits=10, verbose_name='累计充值')),
                ('total_consumed', models.DecimalField(decimal_places=2, default=0, help_text='历史累计消费总额', max_digits=10, verbose_name='累计消费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户余额',
                'verbose_name_plural': '用户余额',
                'db_table': 'sentinel_user_balance',
            },
        ),
        migrations.CreateModel(
            name='TopUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='系统生成的唯一交易标识', max_length=64, unique=True, verbose_name='交易ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='单位：元', max_digits=10, verbose_name='充值金额')),
                ('payment_method', models.CharField(
                    choices=[
                        ('wechat', '微信支付'),
                        ('alipay', '支付宝'),
                        ('card', '银行卡'),
                    ],
                    max_length=10,
                    verbose_name='支付方式'
                )),
                ('status', models.CharField(
                    choices=[
                        ('success', '成功'),
                        ('pending', '处理中'),
                        ('failed', '失败'),
                        ('cancelled', '已取消'),
                    ],
                    default='pending',
                    max_length=10,
                    verbose_name='充值状态'
                )),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'sentinel_topup_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
