# Generated by Django 6.0.4 on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models


def create_default_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')

    defaults = [
        {
            'code': 'monthly',
            'name': '尊享月卡套餐',
            'price': '149.00',
            'duration_days': 30,
            'description': '适合高频通勤，按月计费，灵活续费',
            'is_active': True,
            'sort_order': 10,
        },
        {
            'code': 'quarterly',
            'name': '尊享季卡套餐',
            'price': '399.00',
            'duration_days': 90,
            'description': '季卡优惠，兼顾价格与周期',
            'is_active': True,
            'sort_order': 20,
        },
        {
            'code': 'yearly',
            'name': '尊享年卡套餐',
            'price': '1299.00',
            'duration_days': 365,
            'description': '全年优惠价格，适合长期固定停车用户',
            'is_active': True,
            'sort_order': 30,
        },
    ]

    for item in defaults:
        SubscriptionPlan.objects.update_or_create(
            code=item['code'],
            defaults=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_userbalance_topuprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('monthly', '月卡'), ('quarterly', '季卡'), ('yearly', '年卡')], max_length=20, unique=True, verbose_name='套餐编码')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='套餐价格')),
                ('duration_days', models.PositiveIntegerField(verbose_name='有效天数')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='套餐描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订阅套餐',
                'verbose_name_plural': '订阅套餐',
                'db_table': 'sentinel_subscription_plan',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionplan', verbose_name='套餐信息'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', '月卡'), ('quarterly', '季卡'), ('yearly', '年卡'), ('basic', '基础版'), ('advanced', '高级版'), ('elite', '尊享版')], max_length=10, verbose_name='套餐类型'),
        ),
        migrations.RunPython(create_default_subscription_plans, migrations.RunPython.noop),
    ]
