# Generated by Django 6.0.4 on 2026-04-20

from django.db import migrations, models


def set_default_recommended_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(code='monthly').update(is_recommended=True)


def revert_default_recommended_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model('payments', 'SubscriptionPlan')
    SubscriptionPlan.objects.update(is_recommended=False)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_plan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.RunPython(set_default_recommended_plan, revert_default_recommended_plan),
    ]
