# Generated by Django 6.0.4 on 2026-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='biz_type',
            field=models.CharField(choices=[('parking_fee', '停车缴费'), ('subscription', '套餐订阅'), ('reservation', '车位预定')], default='parking_fee', help_text='交易日志的业务分类', max_length=20, verbose_name='业务类型'),
        ),
    ]
