# Generated by Django 6.0.4 on 2026-05-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_add_biz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='rate_type',
            field=models.CharField(choices=[('hourly_standard', '标准时段（元/小时）'), ('hourly_peak', '高峰时段（元/小时）'), ('hourly_first', '首小时费率（元/小时）'), ('hourly_subsequent', '后续每小时（元/小时）'), ('hourly_switch_hour', '切换日租起始小时数'), ('daily_rate', '日租价（元/天）'), ('daily_cap', '单日封顶（元/天）'), ('reservation_daily', '预约基础费（元/天）'), ('reservation_ev_surcharge', '预约充电桩附加费（元/单）'), ('grace_entry', '入场宽限期（分钟）'), ('grace_exit', '出场宽限期（分钟）'), ('monthly_commute', '月卡-通勤版'), ('monthly_premium', '月卡-高级版')], max_length=32, unique=True, verbose_name='费率类型'),
        ),
    ]
