# Generated by Django 6.0.4 on 2026-05-07 09:49

from django.db import migrations
from decimal import Decimal
import datetime


def add_default_pricing_rules(apps, schema_editor):
    PricingRule = apps.get_model('payments', 'PricingRule')
    today = datetime.date.today()

    defaults = [
        ('hourly_first', '首小时费率', Decimal('6.00'), '元/小时', '停车首小时收费'),
        ('hourly_subsequent', '后续每小时', Decimal('4.00'), '元/小时', '首小时后每小时收费'),
        ('hourly_switch_hour', '切换日租小时数', Decimal('5'), '小时', '超过此小时数切换为日租计费'),
        ('daily_rate', '日租价', Decimal('30.00'), '元/天', '超过5小时后的日租价格'),
        ('daily_cap', '单日封顶', Decimal('60.00'), '元/天', '每日最高收费限额'),
    ]

    for rate_type, desc, value, unit, description in defaults:
        PricingRule.objects.update_or_create(
            rate_type=rate_type,
            defaults={
                'value': value,
                'unit': unit,
                'description': description,
                'is_active': True,
                'effective_date': today,
            }
        )


def remove_default_pricing_rules(apps, schema_editor):
    PricingRule = apps.get_model('payments', 'PricingRule')
    PricingRule.objects.filter(rate_type__in=[
        'hourly_first', 'hourly_subsequent', 'hourly_switch_hour',
        'daily_rate', 'daily_cap',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_add_pricing_rule_types'),
    ]

    operations = [
        migrations.RunPython(add_default_pricing_rules, remove_default_pricing_rules),
    ]
